// Missões 69–100 (faixa 7–8 anos)
export default [
{n:69,e:'🗝️',t:'Caça ao Tesouro com Enigmas',a:'7-8',min:30,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['5 papeizinhos','Lápis','Um prêmio simples no final'],
 hq:['🗝️📜|Uma mensagem em código chegou!','🕵️📞|A Central precisa de alguém esperto.','🧩➡️|Cada pista leva à próxima.','🏆🎉|O baú foi aberto!'],
 c:'Agente, chegou um enigma e só você pode resolver. A primeira pista está no seu travesseiro.',
 p:['Escreva 5 pistas em forma de charada. Ex.: "Onde a comida fica geladinha?" (geladeira).','Esconda cada pista no lugar da resposta da anterior.','A última leva ao prêmio: um lanche especial ou um bilhete carinhoso.'],
 x:'Na próxima vez, a criança cria os enigmas para a família.'},
{n:70,e:'📰',t:'Jornal da Família',a:'7-8',min:30,b:1,m:'S',mo:'chuva',h:'ling',
 mat:['2 folhas de papel','Lápis e lápis de cor'],
 hq:['📰🖨️|O jornal da cidade parou de circular!','✍️📞|A Central quer uma edição nova.','🗞️🖍️|Escreva as notícias da casa.','📢👏|Edição especial nas bancas!'],
 c:'Hoje quem comanda o jornal da família é você. Qual vai ser a manchete de hoje?',
 p:['Dobre as folhas como um jornal e escreva o nome do jornal no topo.','Crie seções: notícia principal, esportes, previsão do tempo, piadas.','Entreviste a família para conseguir as notícias e ilustre.'],
 x:'Faça uma edição por semana e guarde todas numa pasta.'},
{n:71,e:'🌉',t:'Ponte de Papel',a:'7-8',min:20,b:1,m:'S',mo:'jantar',h:'rac',
 mat:['Folhas de papel','2 livros da mesma altura','Moedas ou tampinhas'],
 hq:['🌊🚗|Os carros não conseguem atravessar o rio!','👷📞|A Central chama uma engenharia.','📄🔧|Faça uma ponte só com uma folha.','🪙🏆|Ela aguentou 30 moedas!'],
 c:'Agente, os carros precisam atravessar o rio e você só tem uma folha de papel. Topa o desafio?',
 p:['Afaste os dois livros uns 15 cm.','Primeiro, coloque a folha reta e teste quantas moedas aguenta.','Depois, dobre a folha em sanfona ou em tubo e teste de novo. Qual aguentou mais?'],
 x:'Anote os resultados numa tabela e explique por que a dobra deixou mais forte.'},
{n:72,e:'🎬',t:'Cinema Sem Tela',a:'7-8',min:30,b:1,m:'J',mo:'chuva',h:'ling',
 mat:['Papel para roteiro e ingressos','Fantasias com roupas da casa'],
 hq:['🎬🍿|A família quer ir ao cinema.','📝📞|A Central pede um filme ao vivo!','🎭👗|Escreva, ensaie e se fantasie.','🎟️👏|Sessão lotada!'],
 c:'Hoje tem estreia de filme aqui em casa, só que ao vivo! E quem dirige é você.',
 p:['A criança escreve um roteiro curto: começo, problema e final.','Distribua os papéis e ensaiem uma vez.','Façam ingressos e pipoca e apresentem para quem estiver em casa.'],
 x:'Inclua um "making of": ela conta como criou a história.'},
{n:73,e:'🌋',t:'Vulcão em Erupção',a:'7-8',min:15,b:3,m:'J',mo:'chuva',h:'rac',
 mat:['1 copo ou garrafa pequena','2 colheres de bicarbonato','Vinagre','Detergente e corante (opcional)','1 bandeja'],
 hq:['🌋😴|O vulcão está dormindo.','🧪📞|A Central abre o laboratório.','🥄🧴|Bicarbonato + vinagre...','💥🤩|Erupção!'],
 c:'Agente cientista, o vulcão precisa acordar. Você tem coragem de fazer a erupção?',
 p:['Coloque o copo na bandeja e, dentro, o bicarbonato, um pouco de detergente e corante.','A criança despeja o vinagre aos pouquinhos.','Observem e conversem: o que aconteceu? De onde vieram as bolhas?'],
 x:'Teste com mais e menos vinagre e compare o tamanho da erupção.'},
{n:74,e:'🎲',t:'Crie Seu Jogo de Tabuleiro',a:'7-8',min:40,b:1,m:'S',mo:'chuva',h:'cria',
 mat:['1 folha grande ou cartolina','Lápis de cor','Tampinhas como peões','1 dado (ou papel numerado de 1 a 6)'],
 hq:['🎲📦|A loja de jogos ficou sem novidades.','🧠📞|A Central encomenda um jogo novo.','✏️🗺️|Desenhe o caminho, as casas e as regras.','👨‍👩‍👧🎉|Hora de jogar com a família!'],
 c:'Uma fábrica de jogos quer um jogo novo, inventado por você. Qual vai ser o tema?',
 p:['Escolha um tema: selva, espaço, fundo do mar.','Desenhe uma trilha com 30 casas e casas especiais ("volte 2", "jogue de novo").','Escreva as regras e jogue com a família.'],
 x:'Crie cartas de desafio para quem cair numa casa especial.'},
{n:75,e:'📖',t:'Livro Dobrável',a:'7-8',min:25,b:1,m:'S',mo:'jantar',h:'ling',
 mat:['1 folha de papel','Tesoura','Lápis de cor'],
 hq:['📚❌|A biblioteca perdeu um livro.','✍️📞|A Central precisa de um autor.','📄✂️|Dobre a folha e vire um livrinho.','📖🌟|Livro publicado!'],
 c:'A biblioteca está esperando um livro novo e o autor é você. Sobre o que vai ser?',
 p:['Dobre a folha em 8 partes, faça um corte no meio e monte o livrinho (dá para achar o passo a passo como "livro de uma folha").','Na capa, o título e o nome do autor.','Escreva e desenhe a história, uma cena por página.'],
 x:'Leia o livro para alguém da família antes de dormir.'},
{n:76,e:'🔐',t:'Código Secreto',a:'7-8',min:15,b:1,m:'J',mo:'espera',h:'rac',
 mat:['1 guardanapo ou papel','1 caneta'],
 hq:['🔐📩|Chegou uma mensagem secreta.','🕵️📞|A Central passa o código: A=1, B=2...','🔢➡️🔤|Troque os números por letras.','💌😄|Mensagem decifrada!'],
 c:'Recebi uma mensagem secreta e só um agente consegue decifrar. O código é A=1, B=2, C=3...',
 p:['Escreva no guardanapo o código A=1, B=2... até Z=26.','Escreva uma mensagem curta em números (ex.: 1-13-15 = AMO).','A criança decifra e depois manda uma mensagem codificada para você.'],
 x:'Invente um código novo: com símbolos no lugar das letras.'},
{n:77,e:'🔠',t:'Abecedário da Estrada',a:'7-8',min:15,b:1,m:'J',mo:'viagem',h:'aten',
 mat:['Nenhum'],
 hq:['🔠🛣️|O alfabeto se espalhou pela estrada.','🚗📞|A Central quer o alfabeto completo.','👀🅰️|Ache A, depois B, depois C nas placas.','🏁🏆|Chegou ao Z!'],
 c:'O alfabeto se espalhou pelas placas. Você consegue achar de A a Z, em ordem?',
 p:['Procurem a letra A em placas, outdoors e caminhões.','Quando achar, vale procurar a B. E assim por diante.','Letras difíceis (K, W, Y) podem ser puladas.'],
 x:'Joguem em dupla: cada um procura no seu lado da janela.'},
{n:78,e:'🧳',t:'Na Minha Mala',a:'7-8',min:10,b:1,m:'J',mo:'viagem',h:'aten',
 mat:['Nenhum'],
 hq:['🧳✈️|Vamos viajar e a mala está vazia.','🧠📞|A Central testa a memória.','🗣️➕|Repita tudo e coloque mais uma coisa.','🤯🏅|Que memória!'],
 c:'Eu vou viajar e na minha mala eu levo... uma escova. Agora você repete e coloca mais uma coisa!',
 p:['O primeiro diz: "Na minha mala eu levo uma escova".','O próximo repete e acrescenta: "uma escova e um sapo".','Quem esquecer um item começa uma nova mala.'],
 x:'Só vale colocar coisas em ordem alfabética.'},
{n:79,e:'🤐',t:'Sem Sim, Sem Não',a:'7-8',min:5,b:1,m:'J',mo:'espera',h:'aten',
 mat:['Nenhum'],
 hq:['🤐❗|Duas palavras foram proibidas!','📞⚠️|A Central avisa: nada de "sim" ou "não".','💬😏|Responda as perguntas sem cair na armadilha.','😂🏆|Escapou!'],
 c:'Agora são proibidas as palavras "sim" e "não". Quanto tempo você aguenta sem falar?',
 p:['Faça perguntas rápidas: "Você gosta de pizza?"','A criança tem que responder sem dizer "sim" nem "não" ("Eu adoro!").','Quem falar perde e troca de lugar.'],
 x:'Proíba também "eu" para deixar mais difícil.'},
{n:80,e:'✍️',t:'Adedonha',a:'7-8',min:15,b:1,m:'J',mo:'espera',h:'ling',
 mat:['Papel e caneta'],
 hq:['✍️🔤|Começa o campeonato de palavras!','🤚📞|A Central sorteia a letra.','🍎🐶|Nome, fruta, bicho e cor com a mesma letra.','🛑🏆|Stop!'],
 c:'Vamos jogar adedonha? Nome, fruta, bicho e cor. Valendo!',
 p:['Faça 4 colunas: nome, fruta, bicho, cor.','Sorteie uma letra (contando nos dedos).','Todos escrevem uma palavra para cada coluna. Quem terminar grita "Stop!".'],
 x:'Inclua colunas novas: cidade, objeto, comida.'},
{n:81,e:'🔲',t:'Batalha dos Quadradinhos',a:'7-8',min:10,b:1,m:'J',mo:'espera',h:'rac',
 mat:['1 guardanapo ou papel','1 caneta'],
 hq:['🔲⚔️|Começou a batalha dos quadradinhos!','📞✏️|A Central desenha o campo de pontos.','➖🔳|Ligue os pontos e feche quadrados.','🏆😄|Quem fechou mais venceu!'],
 c:'Duelo de estratégia: quem fechar mais quadradinhos vence. Topa?',
 p:['Desenhe uma grade de 5 x 5 pontinhos.','Cada um, na sua vez, liga dois pontos vizinhos.','Quem fechar um quadrado escreve sua inicial dentro e joga de novo.'],
 x:'Aumente para 8 x 8 pontos.'},
{n:82,e:'🍰',t:'Mestre da Receita',a:'7-8',min:30,b:2,m:'J',mo:'jantar',h:'rac',
 mat:['Uma receita simples (bolo de caneca, vitamina, biscoito)','Xícaras e colheres medidoras'],
 hq:['📜🍰|Uma receita antiga foi encontrada!','👨‍🍳📞|A Central entrega a receita para você.','🥄⚖️|Leia e meça cada ingrediente.','😋🎉|Ficou delicioso!'],
 c:'Hoje quem comanda a cozinha é você: lê a receita e mede tudo. Eu só ajudo.',
 p:['Escolham uma receita fácil e leiam juntos.','A criança mede os ingredientes: meia xícara, duas colheres.','O adulto cuida do fogão e do forno.'],
 x:'Dobre a receita: quanto de cada ingrediente vai precisar?'},
{n:83,e:'🛒',t:'Lanche com R$ 20',a:'7-8',min:20,b:1,m:'J',mo:'jantar',h:'rac',
 mat:['Folheto de mercado (ou preços inventados)','Papel e lápis'],
 hq:['💵🛒|Você ganhou R$ 20 para o lanche da família.','🧮📞|A Central quer um plano de compras.','📝➕|Escolha os itens sem passar do valor.','✅😋|Lanche planejado!'],
 c:'Você tem R$ 20 para montar o lanche de sábado da família. O que dá para comprar?',
 p:['Mostre os preços (folheto ou inventados).','A criança escolhe itens e vai somando no papel.','Ela não pode passar de R$ 20. Sobrou troco?'],
 x:'No mercado de verdade, ela confere os preços com a lista.'},
{n:84,e:'🔷',t:'Tangram de Papel',a:'7-8',min:20,b:1,m:'S',mo:'jantar',h:'rac',
 mat:['1 folha quadrada','Régua, lápis e tesoura'],
 hq:['🔷🧩|Um quadrado se quebrou em 7 peças.','🐱📞|A Central diz: dá para formar bichos!','✂️🔺|Recorte as peças do tangram.','🐈🏠|Formou um gato e uma casa!'],
 c:'Com essas 7 peças você pode formar qualquer coisa. Consegue montar um gato?',
 p:['Desenhe o tangram num quadrado (2 triângulos grandes, 1 médio, 2 pequenos, 1 quadrado, 1 paralelogramo).','A criança recorta as peças.','Ela tenta montar figuras: gato, casa, barco, pessoa.'],
 x:'Monte uma figura e desafie a família a copiar.'},
{n:85,e:'✈️',t:'Aviões Campeões',a:'7-8',min:20,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['3 folhas de papel','Fita métrica ou passos para medir'],
 hq:['✈️🏁|Começou o campeonato de aviões!','📐📞|A Central quer o avião que voa mais longe.','📄✈️|Dobre 3 modelos diferentes.','📏🥇|Recorde de distância!'],
 c:'Qual avião de papel voa mais longe? Vamos testar 3 modelos como cientistas.',
 p:['Dobrem 3 modelos diferentes (ponta fina, asas largas, inventado).','Lancem cada um 3 vezes do mesmo lugar.','Meçam com passos e anotem. Qual venceu?'],
 x:'Teste um clipe na ponta do avião. Ele voa melhor ou pior?'},
{n:86,e:'🙈',t:'Desenho às Cegas',a:'7-8',min:10,b:1,m:'J',mo:'cinco',h:'cria',
 mat:['Papel e lápis'],
 hq:['🙈✏️|O desafio de hoje é desenhar sem olhar!','🎨📞|A Central dá o tema.','🐘🤭|Desenhe de olhos fechados.','😂🖼️|Que obra de arte!'],
 c:'Desafio: desenhar um elefante de olhos fechados. Quem fizer o mais engraçado ganha!',
 p:['Escolham um tema: elefante, casa, a pessoa ao lado.','Todos desenham de olhos fechados por 1 minuto.','Abram os olhos e riam juntos dos resultados.'],
 x:'Um descreve um desenho e o outro tenta desenhar sem ver o original.'},
{n:87,e:'⚖️',t:'Debate Maluco',a:'7-8',min:10,b:1,m:'J',mo:'espera',h:'ling',
 mat:['Nenhum'],
 hq:['⚖️🍕|Uma grande dúvida chegou à Central!','🎙️📞|"Pizza ou sorvete: qual é melhor?"','🗣️💡|Defenda a sua opinião com 3 motivos.','👏🤝|Bom debate!'],
 c:'Grande debate: o que é melhor, ser um peixe ou ser um passarinho? Me convença!',
 p:['Lance uma pergunta divertida.','A criança escolhe um lado e dá 3 motivos.','Você defende o outro lado. No final, troquem de lado.'],
 x:'Ela inventa a próxima pergunta do debate.'},
{n:88,e:'📔',t:'Diário de Bordo',a:'7-8',min:10,b:1,m:'S',mo:'dormir',h:'emo',
 mat:['1 caderno','Lápis'],
 hq:['📔🚀|Todo explorador tem um diário.','✍️📞|A Central pede o relatório do dia.','🌤️😊|Escreva o que fez e o que sentiu.','🌙😴|Relatório entregue. Boa noite!'],
 c:'Todo explorador escreve o diário de bordo antes de dormir. O que aconteceu na sua missão de hoje?',
 p:['Separe um caderno só para o diário.','A criança escreve 3 frases: o que fez, o que sentiu, o que quer amanhã.','Pode desenhar em vez de escrever nos dias de preguiça.'],
 x:'Uma vez por semana, leiam juntos as páginas antigas.'},
{n:89,e:'🔦',t:'Leitura de Lanterna',a:'7-8',min:15,b:1,m:'S',mo:'dormir',h:'ling',
 mat:['1 lanterna','1 livro','1 lençol (opcional, para a cabana)'],
 hq:['🌙📚|O quarto ficou escuro.','🔦📞|A Central libera a leitura secreta.','🛏️📖|Leia com a lanterna debaixo do lençol.','😴⭐|Dormiu no meio da aventura.'],
 c:'Hoje você tem permissão especial: 15 minutos de leitura com lanterna antes de dormir.',
 p:['Apague a luz do quarto e entregue a lanterna.','A criança lê sozinha, debaixo do lençol ou numa cabana.','Combine o tempo: quando a lanterna apagar, é hora de dormir.'],
 x:'Peça para ela contar no café da manhã o que leu.'},
{n:90,e:'🤹',t:'Malabarista de Meias',a:'7-8',min:10,b:1,m:'S',mo:'cinco',h:'motora',
 mat:['3 pares de meias enroladas'],
 hq:['🎪🤹|O circo precisa de um malabarista!','🧦📞|A Central manda 3 bolinhas de meia.','⬆️⬆️|Comece com 1, depois 2, depois 3.','🎉👏|Respeitável público!'],
 c:'O circo vai começar e falta o número de malabares. Você aprende a jogar 2 bolinhas ao mesmo tempo?',
 p:['Comece jogando 1 meia de uma mão para a outra, em arco.','Depois 2 meias: joga a primeira e, quando ela estiver no alto, joga a segunda.','Quem conseguir, tenta com 3.'],
 x:'Conte quantas trocas consegue sem deixar cair.'},
{n:91,e:'🎶',t:'Paródia da Família',a:'7-8',min:20,b:1,m:'J',mo:'viagem',h:'cria',
 mat:['Nenhum'],
 hq:['🎶🚗|A rádio do carro quebrou!','🎤📞|A Central pede uma música nova.','✍️🎵|Invente uma letra para uma música conhecida.','🎉😂|Sucesso da viagem!'],
 c:'A rádio quebrou e a gente vai ter que fazer as músicas. Vamos inventar uma letra nova para "Atirei o Pau no Gato"?',
 p:['Escolham uma música que todos sabem.','Troquem a letra para falar da família, do cachorro ou da viagem.','Cantem juntos e repitam até decorar.'],
 x:'Cada pessoa da família ganha uma estrofe.'},
{n:92,e:'🚦',t:'Bingo da Estrada',a:'7-8',min:20,b:1,m:'S',mo:'viagem',h:'aten',
 mat:['1 cartela feita antes da viagem (papel e lápis)'],
 hq:['🚦🎰|Começou o bingo da estrada!','📋📞|A Central entrega as cartelas.','👀🐄|Viu uma vaca? Marque!','🎉🗣️|BINGO!'],
 c:'Preparei uma cartela de bingo da estrada. Quando você vir tudo de uma linha, grita BINGO!',
 p:['Antes de sair, faça uma cartela com 9 quadrados: vaca, caminhão vermelho, ponte, placa de 80, moto, ônibus, árvore com flor, cavalo, posto.','A criança marca cada coisa que vê.','Completou uma linha, grita "Bingo!".'],
 x:'Ela cria a cartela para a próxima viagem.'},
{n:93,e:'💌',t:'Bilhetes Secretos de Carinho',a:'7-8',min:10,b:1,m:'S',mo:'dormir',h:'emo',
 mat:['Papeizinhos','Lápis'],
 hq:['💌🤫|A Central tem uma missão de carinho.','✍️💛|Escreva bilhetes gentis para a família.','🙈🧦|Esconda em lugares surpresa.','😍☀️|Amanhã todos vão encontrar!'],
 c:'Missão secreta: espalhar bilhetes de carinho pela casa sem ninguém ver. Você aceita?',
 p:['A criança escreve 3 bilhetes curtos: "Você é especial", "Obrigado por...".','À noite, ela esconde num sapato, no travesseiro ou na lancheira.','No dia seguinte, observe a reação de quem encontrar.'],
 x:'Repita uma vez por semana: vira tradição da família.'},
{n:94,e:'🏛️',t:'Museu da Casa',a:'7-8',min:30,b:1,m:'S',mo:'chuva',h:'ling',
 mat:['Objetos da casa','Papeizinhos para etiquetas','Lápis'],
 hq:['🏛️🔒|O museu da casa está fechado.','🗝️📞|A Central entrega a chave do museu.','🏷️🧸|Escolha objetos e escreva as etiquetas.','🎟️👏|Visita guiada para a família!'],
 c:'Hoje o Museu da Casa é seu. Que objetos vão entrar na exposição?',
 p:['A criança escolhe 6 objetos com história (um brinquedo antigo, uma foto, uma concha).','Para cada um, escreve uma etiqueta: nome, ano e uma curiosidade.','Ela faz uma visita guiada para a família.'],
 x:'Peça para entrevistar os avós sobre um objeto antigo.'},
{n:95,e:'⏱️',t:'Desafio do Minuto',a:'7-8',min:10,b:1,m:'J',mo:'cinco',h:'motora',
 mat:['Copos plásticos','Meias','1 relógio para contar o minuto'],
 hq:['⏱️🔥|Você tem só 1 minuto!','📣📞|A Central lança os desafios.','🥤🧦|Empilhe copos, jogue meias, equilibre.','🏆😄|Desafio vencido!'],
 c:'Cada desafio dura só um minuto. Você aguenta a pressão?',
 p:['Prepare 3 desafios: empilhar 10 copos, acertar 5 meias no cesto, equilibrar num pé só.','Conte 1 minuto para cada um.','Anote o resultado e tente bater na próxima rodada.'],
 x:'A criança inventa um desafio novo para você.'},
{n:96,e:'🌀',t:'Labirinto para o Adulto',a:'7-8',min:20,b:1,m:'S',mo:'espera',h:'rac',
 mat:['Papel ou guardanapo','Caneta'],
 hq:['🌀😵|Os adultos estão entediados.','🧠📞|A Central pede um labirinto bem difícil.','✏️🧩|Desenhe caminhos falsos e um certo.','🏁😮|O adulto conseguiu sair?'],
 c:'Faça um labirinto bem difícil para mim. Vou tentar sair sem errar!',
 p:['Mostre como começar: entrada, saída e um caminho certo.','A criança desenha caminhos falsos em volta para confundir.','Você tenta resolver. Ela pode dar dicas se você empacar.'],
 x:'Coloque um tesouro no meio do labirinto que precisa ser pego no caminho.'},
{n:97,e:'📻',t:'Rádio do Carro',a:'7-8',min:15,b:1,m:'J',mo:'viagem',h:'ling',
 mat:['Nenhum'],
 hq:['📻📡|Atenção, ouvintes!','🎙️📞|A Central abre a rádio da família.','🌦️⚽|Notícias, previsão do tempo e esportes.','👏📻|Melhor programa da estrada!'],
 c:'Está no ar a Rádio da Família! E quem apresenta hoje é você.',
 p:['A criança apresenta o programa: "Bom dia, ouvintes!".','Ela dá notícias da viagem, a previsão do tempo e um "comercial" inventado.','Os passageiros podem "ligar" para a rádio com perguntas.'],
 x:'Inclua uma entrevista com um passageiro.'},
{n:98,e:'🍽️',t:'Garçom Profissional',a:'7-8',min:15,b:1,m:'S',mo:'jantar',h:'auto',
 mat:['Pratos, talheres, copos e guardanapos'],
 hq:['🍽️😬|A mesa do jantar está vazia.','🤵📞|A Central quer uma mesa de restaurante.','🍴🥄|Garfo à esquerda, faca e colher à direita.','✨🛎️|Mesa de restaurante chique!'],
 c:'Hoje o nosso jantar vai ser de restaurante chique. Você arruma a mesa como nos restaurantes?',
 p:['Mostre uma vez: prato no centro, garfo à esquerda, faca e colher à direita, copo em cima.','A criança arruma a mesa para todos.','Ensine a dobrar o guardanapo em triângulo.'],
 x:'Ela anuncia o jantar: "O jantar está servido!".'},
{n:99,e:'✉️',t:'Carta para o Futuro',a:'7-8',min:20,b:1,m:'S',mo:'dormir',h:'emo',
 mat:['Papel e lápis','1 envelope'],
 hq:['⏳✉️|A Central abriu o correio do tempo.','🔮📞|Escreva para você daqui a 1 ano.','✍️💭|Conte seus gostos, medos e sonhos.','🔒📅|Guarde até a data marcada!'],
 c:'E se você pudesse mandar uma carta para você mesmo daqui a um ano? O que contaria?',
 p:['A criança escreve: idade, melhores amigos, comida preferida, o que quer aprender.','Ela fecha o envelope e escreve a data de abertura.','Guardem num lugar especial e coloquem um lembrete no calendário.'],
 x:'Escreva você também uma carta para ela abrir no mesmo dia.'},
{n:100,e:'🏆',t:'Olimpíada da Família',a:'7-8',min:40,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['Medalhas de papel','Copos, colheres, meias e almofadas para as provas'],
 hq:['🏟️🎺|Começou a Olimpíada da Família!','🏅📞|A Central organiza as provas.','🥄🥚|Corrida da colher, arremesso de meia, salto.','🥇🎉|Todo mundo no pódio!'],
 c:'Atenção, atletas: começou a Olimpíada da Família! Quem organiza as provas é você.',
 p:['A criança faz as medalhas de papel e escolhe 4 provas.','Exemplos: corrida com bolinha na colher, arremesso de meia, salto em distância, equilíbrio.','Anotem os pontos e terminem com a cerimônia do pódio.'],
 x:'Crie uma bandeira e um hino para a família.'},
];
