// Missões 35–68 (faixa 5–6 anos)
export default [
{n:35,e:'🏴‍☠️',t:'Mapa do Tesouro',a:'5-6',min:25,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['1 folha de papel','Lápis de cor','Um "tesouro" (um brinquedo ou um bilhete carinhoso)'],
 hq:['🏴‍☠️💰|Um pirata escondeu um tesouro na casa!','🗺️📞|A Central encontrou um mapa.','✏️❌|Siga o mapa até o X.','💎🎉|Tesouro encontrado!'],
 c:'Um pirata escondeu um tesouro aqui em casa e deixou um mapa. Você consegue achar?',
 p:['Desenhe juntos um mapa simples da casa: sala, cozinha, quartos.','Esconda o tesouro e marque um X no mapa.','A criança usa o mapa para encontrar.'],
 x:'Ela desenha o mapa e esconde o tesouro para você achar.'},
{n:36,e:'🧦',t:'Teatro de Meias',a:'5-6',min:25,b:2,m:'J',mo:'chuva',h:'ling',
 mat:['2 meias velhas','Canetinha, lã ou botões para os olhos (com adulto)','1 mesa virada ou caixa como palco'],
 hq:['🎭🚪|O teatro está sem atores!','🧦📞|A Central transforma meias em fantoches.','✍️👀|Desenhe olhos e boca na meia.','👏🎬|Que espetáculo!'],
 c:'O teatro vai abrir hoje à noite e os atores ainda não existem. Vamos criar?',
 p:['Coloque a meia na mão da criança e marque onde ficam os olhos e a boca.','Ela desenha a cara do personagem e dá um nome.','Escondam-se atrás do sofá e apresentem uma história curta.'],
 x:'Façam ingressos de papel e chamem a família para assistir.'},
{n:37,e:'🍝',t:'Restaurante em Casa',a:'5-6',min:20,b:1,m:'S',mo:'jantar',h:'ling',
 mat:['Papel e lápis de cor','1 caneta e um bloquinho para os pedidos'],
 hq:['🍽️📋|O restaurante vai abrir e não tem cardápio!','👨‍🍳📞|A Central chama você para comandar o restaurante.','🖍️📝|Desenhe o cardápio e anote os pedidos.','🛎️😋|O jantar está servido!'],
 c:'O nosso restaurante abre hoje no jantar. Você faz o cardápio e anota os pedidos?',
 p:['A criança desenha um cardápio com os pratos do jantar de hoje.','Ela passa nas pessoas da casa anotando os pedidos (com desenho ou letras).','Na hora de servir, ela é a garçonete.'],
 x:'Invente preços e faça a "conta" no final do jantar.'},
{n:38,e:'🗼',t:'Torre Gigante',a:'5-6',min:15,b:1,m:'S',mo:'jantar',h:'rac',
 mat:['Copos plásticos, potes ou blocos','Fita métrica (opcional)'],
 hq:['🏙️📏|A cidade precisa do prédio mais alto!','🏗️📞|A Central chama a equipe de construção.','🥤🥤|Empilhe sem deixar cair.','🗼🥇|Recorde batido!'],
 c:'A cidade quer o prédio mais alto do mundo. Você consegue construir sem derrubar?',
 p:['Separe copos plásticos, potes vazios ou blocos.','A criança empilha a torre mais alta que conseguir.','Meçam com a fita ou com palmos e anotem o recorde.'],
 x:'Tente uma torre usando só 10 peças e veja quem faz a mais alta.'},
{n:39,e:'🖐️',t:'Bicho de Mão',a:'5-6',min:15,b:1,m:'S',mo:'chuva',h:'cria',
 mat:['Papel','Lápis e lápis de cor'],
 hq:['🖐️❓|Uma mão perdida virou um mistério.','🦃📞|A Central diz: ela pode virar um bicho!','✏️🎨|Contorne a mão e transforme.','🦚😍|Nasceu um bicho novo!'],
 c:'A sua mão pode virar um bicho. Qual será que aparece hoje?',
 p:['A criança contorna a própria mão no papel.','Ela transforma o desenho num bicho: peru, polvo, leão, peixe.','Dê um nome para o bicho e uma história curta.'],
 x:'Contorne a mão de alguém da família e faça um bicho diferente.'},
{n:40,e:'🌈',t:'Arco-íris de Papel',a:'5-6',min:25,b:2,m:'J',mo:'chuva',h:'cria',
 mat:['Revistas velhas ou papéis coloridos','1 folha com um arco-íris desenhado','Cola'],
 hq:['🌈🖤|O arco-íris perdeu as cores.','📰📞|A Central encontrou papéis coloridos.','✂️🖐️|Rasgue e cole cada cor no lugar.','🌈✨|Arco-íris novinho!'],
 c:'O arco-íris ficou sem cor. Você consegue devolver as cores dele com papel?',
 p:['Desenhe um arco-íris grande só com o contorno.','A criança rasga pedacinhos de papel de cada cor (rasgar treina os dedos).','Ela cola cada cor na sua faixa.'],
 x:'Desenhe nuvens dos lados e cole algodão em cima.'},
{n:41,e:'🎨',t:'Pintor Mirim',a:'5-6',min:20,b:2,m:'S',mo:'jantar',h:'fina',
 mat:['Aquarela ou guache','Cotonetes e pincel','Papel e um pote de água'],
 hq:['🖼️⬜|O museu está com uma parede vazia.','🎨📞|A Central encomenda uma pintura.','🖌️🔵|Pinte com pincel e com bolinhas de cotonete.','🏛️👏|Obra pronta para o museu!'],
 c:'O museu precisa de uma obra nova até o jantar. Você pinta para mim?',
 p:['Forre a mesa com jornal e prepare a tinta e a água.','Mostre como fazer bolinhas de tinta com o cotonete.','Deixe a criança pintar livremente. Pendure a obra quando secar.'],
 x:'Pinte um desenho inteiro só com bolinhas de cotonete.'},
{n:42,e:'🔤',t:'Caça às Letras',a:'5-6',min:15,b:1,m:'J',mo:'cinco',h:'ling',
 mat:['Nenhum'],
 hq:['🔤😮|As letras fugiram do alfabeto!','🕵️📞|A Central precisa encontrá-las.','🏠🅱️|Ache coisas que começam com B.','✅🔠|Letras recuperadas!'],
 c:'A letra B fugiu e está escondida nas coisas da casa. Quantas coisas com B você acha?',
 p:['Escolha uma letra, por exemplo B.','A criança procura objetos que começam com essa letra: bola, banana, boné.','Troquem de letra a cada rodada.'],
 x:'Procure coisas que começam com a primeira letra do nome dela.'},
{n:43,e:'🛋️',t:'Guerra de Almofadas',a:'5-6',min:10,b:1,m:'J',mo:'cinco',h:'vinc',
 mat:['Almofadas macias'],
 hq:['😴🛋️|A família está muito parada.','📯📞|A Central declara: guerra de almofadas!','🛋️💥|Ataque só abaixo do ombro.','🤣💛|Todo mundo rindo junto.'],
 c:'Atenção: começou a guerra de almofadas! Mas tem regras. Você topa?',
 p:['Combinem as regras: só almofadas macias e só abaixo do ombro.','Quem falar "pausa" para tudo na hora.','Brinquem 5 minutos e terminem com um abraço de almofada.'],
 x:'Termine com todos deitados no chão contando até 20 para acalmar.'},
{n:44,e:'🖼️',t:'Minha Obra-Prima',a:'5-6',min:20,b:1,m:'S',mo:'jantar',h:'ling',
 mat:['Papel e lápis de cor','1 tirinha de papel para a "placa"'],
 hq:['🏛️🎟️|O museu da casa vai inaugurar.','🖼️📞|A Central quer uma obra-prima.','✏️🖍️|Desenhe e escreva o título na placa.','🎤👏|Apresente a obra para a família!'],
 c:'Hoje inaugura o museu da nossa casa e quem expõe é você!',
 p:['A criança faz o desenho que quiser.','Ela escreve (ou dita) o título e o nome dela numa tirinha de papel.','No jantar, ela apresenta a obra: o que desenhou e por quê.'],
 x:'Monte uma exposição na parede com 3 obras e cobre ingresso de abraço.'},
{n:45,e:'🚀',t:'Foguete de Rolo',a:'5-6',min:20,b:2,m:'J',mo:'chuva',h:'fina',
 mat:['1 rolo de papel higiênico vazio','Papel colorido','Cola e tesoura sem ponta','Lápis de cor'],
 hq:['🚀🌑|Um astronauta precisa ir à Lua!','🛠️📞|A Central pede um foguete.','✂️🧻|Use o rolo, papel e cola.','🌕🎉|3, 2, 1... decolar!'],
 c:'O astronauta precisa ir para a Lua hoje e o foguete ainda não existe. Vamos construir?',
 p:['Encape o rolo com papel colorido.','Faça um cone de papel para a ponta e asas para os lados.','A criança decora e faz a contagem regressiva para decolar.'],
 x:'Desenhe planetas e pendure no quarto para o foguete visitar.'},
{n:46,e:'🎳',t:'Boliche de Garrafas',a:'5-6',min:15,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['6 garrafas PET com um pouco de água','1 bola ou meias enroladas'],
 hq:['🎳🏟️|O campeonato de boliche vai começar!','📞🏆|A Central chama os jogadores.','🎯💨|Role a bola e derrube os pinos.','🥇😄|Strike!'],
 c:'O campeonato de boliche começou. Quantos pinos você derruba na primeira jogada?',
 p:['Coloque um pouco de água nas garrafas e arrume em triângulo.','Marque o lugar de jogar a uns 2 metros.','Cada um tem 2 jogadas por rodada. Anotem os pontos.'],
 x:'A criança anota o placar e soma os pontos no fim.'},
{n:47,e:'🔦',t:'Caça com Lanterna',a:'5-6',min:15,b:1,m:'J',mo:'chuva',h:'aten',
 mat:['1 lanterna','8 papeizinhos com desenhos de estrelas'],
 hq:['🌑⭐|As estrelas caíram dentro de casa!','🔦📞|A Central entrega uma lanterna.','🔍✨|Procure no escuro e recolha todas.','🌌😍|O céu está completo!'],
 c:'As estrelas caíram do céu e se esconderam no escuro. Você consegue achar as 8?',
 p:['Espalhe as estrelas de papel num cômodo.','Apague a luz e entregue a lanterna.','A criança procura e devolve as estrelas para o "céu" (uma caixa).'],
 x:'Esconda uma estrela "dourada" que vale prêmio especial: um abraço apertado.'},
{n:48,e:'👀',t:'Eu Espio',a:'5-6',min:5,b:1,m:'J',mo:'espera',h:'aten',
 mat:['Nenhum'],
 hq:['🍽️⏳|A comida está demorando...','👀📞|A Central ativa o modo espião.','🔵🤔|"Eu espio uma coisa azul..."','💡😄|Adivinhou!'],
 c:'Eu estou espiando uma coisa azul aqui perto. Você consegue descobrir o que é?',
 p:['Escolha algo que os dois conseguem ver.','Diga só a cor: "Eu espio uma coisa vermelha".','A criança adivinha. Depois ela escolhe e você adivinha.'],
 x:'Em vez da cor, diga a letra inicial: "uma coisa que começa com M".'},
{n:49,e:'🗣️',t:'História em Cadeia',a:'5-6',min:10,b:1,m:'J',mo:'viagem',h:'ling',
 mat:['Nenhum'],
 hq:['🚗😴|A viagem está longa.','📖📞|A Central começa uma história.','🗣️➡️|Cada um fala uma frase.','😂🎉|Que história maluca!'],
 c:'Vamos inventar uma história juntos? Eu começo e você continua: "Era uma vez um sapo que..."',
 p:['Um adulto começa com uma frase.','A criança continua com a próxima frase.','Vão revezando até a história ter um final.'],
 x:'Cada frase precisa ter uma cor ou um animal novo.'},
{n:50,e:'🔢',t:'Caçador de Números',a:'5-6',min:15,b:1,m:'J',mo:'viagem',h:'rac',
 mat:['Nenhum'],
 hq:['🔢🛣️|Os números se esconderam na estrada.','🚗📞|A Central pede ajuda.','👀1️⃣|Ache o 1, depois o 2, depois o 3...','🔟🏆|Chegou ao 10!'],
 c:'Os números se esconderam nas placas e nos carros. Você acha do 1 até o 10, em ordem?',
 p:['A criança procura o número 1 em placas, ônibus ou carros.','Quando achar, passa para o 2, depois o 3.','O objetivo é chegar ao 10.'],
 x:'Para as maiores: de 10 até 20.'},
{n:51,e:'🧻',t:'Rabisco Mágico',a:'5-6',min:10,b:1,m:'S',mo:'espera',h:'cria',
 mat:['1 guardanapo ou papel','1 caneta'],
 hq:['〰️❓|Apareceu um rabisco misterioso!','🪄📞|A Central diz: ele pode virar qualquer coisa.','✏️🐶|Complete e transforme o rabisco.','🖼️😄|Virou um desenho!'],
 c:'Eu faço um rabisco qualquer e você transforma em um desenho. Vamos ver o que vira?',
 p:['Faça um rabisco simples no guardanapo.','A criança completa e transforma em bicho, pessoa ou objeto.','Ela conta o que desenhou.'],
 x:'Troquem: ela rabisca e você transforma.'},
{n:52,e:'👏',t:'Palmas Espelho',a:'5-6',min:5,b:1,m:'J',mo:'espera',h:'aten',
 mat:['Nenhum'],
 hq:['👏🎵|A Central mandou um ritmo secreto.','👂📞|Escute com atenção.','👏👏🤚|Repita igualzinho.','🥁🏅|Que ouvido!'],
 c:'Eu vou bater um ritmo com as palmas. Você consegue repetir igualzinho?',
 p:['Bata um ritmo curto com as palmas (3 batidas).','A criança repete.','Aumente aos poucos: 4, 5, 6 batidas, misturando palma e batida na mesa.'],
 x:'Ela cria o ritmo e você repete.'},
{n:53,e:'🥗',t:'Salada Colorida',a:'5-6',min:20,b:2,m:'J',mo:'jantar',h:'auto',
 mat:['Folhas de alface','Tomate-cereja, cenoura ralada, milho','Tigela e faca sem ponta'],
 hq:['🥗🎨|O jantar está sem cor.','👩‍🍳📞|A Central pede uma salada especial.','🥬🍅|Lave, rasgue e monte o prato.','🌈😋|A salada mais colorida do mundo!'],
 c:'O jantar precisa de uma salada bem colorida. Você prepara a salada hoje?',
 p:['A criança lava as folhas e rasga com as mãos.','Ela corta os tomatinhos ao meio com a faca sem ponta (com supervisão).','Monta o prato misturando as cores.'],
 x:'Desafio: usar pelo menos 4 cores diferentes.'},
{n:54,e:'👕',t:'Ajudante da Roupa',a:'5-6',min:15,b:1,m:'S',mo:'jantar',h:'auto',
 mat:['Roupas limpas para separar','Panos de prato'],
 hq:['👕🌪️|As roupas limpas estão misturadas.','🧺📞|A Central pede reforço.','👚👖|Separe por dono e dobre os panos.','🗂️✨|Tudo organizado!'],
 c:'A loja de roupas precisa de alguém para organizar. Você separa de quem é cada roupa?',
 p:['Coloque as roupas limpas num cesto.','A criança separa em montes: de cada pessoa da casa.','Mostre como dobrar pano de prato e deixe ela dobrar todos.'],
 x:'Cronometre e tente fazer mais rápido na próxima vez.'},
{n:55,e:'📏',t:'Medidor Oficial',a:'5-6',min:15,b:1,m:'S',mo:'chuva',h:'rac',
 mat:['Papel e lápis','Um objeto para medir: o próprio pé, um lápis ou um palmo'],
 hq:['📏❓|Ninguém sabe o tamanho das coisas!','📐📞|A Central nomeia um medidor oficial.','🦶🛋️|Meça o sofá com pés e a mesa com palmos.','📋🏅|Relatório entregue!'],
 c:'Quantos pés tem o sofá? Hoje quem mede tudo na casa é você!',
 p:['A criança escolhe uma "régua": o pé, o palmo ou um lápis.','Ela mede o sofá, a mesa, a cama e a porta.','Anota os números (ou desenha tracinhos) num papel.'],
 x:'Meça a mesma coisa com o seu pé e com o dela. Por que deu diferente?'},
{n:56,e:'🕸️',t:'Teia de Espião',a:'5-6',min:20,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['Barbante ou fita crepe','2 cadeiras ou um corredor'],
 hq:['🕸️🚨|O corredor está protegido por raios laser!','🕵️📞|A Central precisa de alguém bem ágil.','🤸🧶|Passe sem encostar nos fios.','🏁😎|Missão concluída!'],
 c:'O cofre está do outro lado e o caminho tem raios laser. Você passa sem encostar?',
 p:['Prenda barbante ou fita crepe cruzando o corredor em alturas diferentes.','A criança passa por cima e por baixo sem tocar.','Coloque um "cofre" (brinquedo) no fim do caminho.'],
 x:'Passe carregando um copo de plástico sem deixar cair.'},
{n:57,e:'🎤',t:'Repórter da Família',a:'5-6',min:15,b:1,m:'J',mo:'jantar',h:'ling',
 mat:['1 colher de pau ou escova de cabelo (vira microfone)'],
 hq:['📺📰|O jornal vai entrar no ar!','🎤📞|A Central abre o microfone.','❓👨‍👩‍👧|Entreviste cada pessoa da casa.','🎬👏|Notícia no ar!'],
 c:'O jornal da noite vai começar e quem faz as perguntas é você. Quem vai ser entrevistado primeiro?',
 p:['Entregue o "microfone" para a criança.','Ela faz perguntas: "Qual sua comida preferida? O que você fez hoje?"','No final, ela conta as notícias do dia para todos.'],
 x:'Faça uma previsão do tempo inventada: "Amanhã vai chover chocolate!"'},
{n:58,e:'💛',t:'Três Coisas Boas',a:'5-6',min:5,b:1,m:'J',mo:'dormir',h:'emo',
 mat:['Nenhum'],
 hq:['🌙🧠|O dia acabou.','💛📞|A Central quer saber as coisas boas.','1️⃣2️⃣3️⃣|Conte 3 momentos bons de hoje.','😴😊|Dormir com o coração quentinho.'],
 c:'Antes de dormir, me conta: quais foram as 3 coisas mais legais do seu dia?',
 p:['Deitados na cama, cada um fala 3 coisas boas do dia.','Ouça com atenção e pergunte: "O que você sentiu?"','Termine contando uma coisa boa que ela fez hoje.'],
 x:'Faça todas as noites: vira um hábito de gratidão.'},
{n:59,e:'☁️',t:'Viagem para as Nuvens',a:'5-6',min:5,b:1,m:'J',mo:'dormir',h:'emo',
 mat:['Nenhum'],
 hq:['☁️🛏️|A cama virou uma nuvem.','🌬️📞|A Central guia a viagem.','🦶😌|Solte os pés, as pernas, a barriga...','😴🌙|Chegou ao céu dos sonhos.'],
 c:'Feche os olhos. A sua cama virou uma nuvem macia e nós vamos viajar devagarinho.',
 p:['Com voz baixa, peça para a criança soltar os pés, como se ficassem moles.','Suba devagar: pernas, barriga, braços, ombros, rosto.','Descreva a nuvem flutuando bem devagar até o céu dos sonhos.'],
 x:'Pergunte que cor tem a nuvem e para onde ela gostaria de ir.'},
{n:60,e:'🎲',t:'Dado Gigante',a:'5-6',min:20,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['1 caixa quadrada','Papel, fita e caneta'],
 hq:['🎲📦|Uma caixa virou um dado gigante!','🏋️📞|A Central inventa um treino.','🔢🤸|Cada número é um exercício.','💪😄|Treino concluído!'],
 c:'Esse dado gigante manda na gente. O que ele mandar, a gente faz!',
 p:['Encape a caixa e desenhe as bolinhas de 1 a 6.','Combinem um exercício para cada número: 1 pular, 2 girar, 3 agachar...','Jogue o dado e façam o exercício o número de vezes que cair.'],
 x:'A criança inventa os exercícios.'},
{n:61,e:'✂️',t:'Salão de Beleza do Papel',a:'5-6',min:15,b:1,m:'S',mo:'jantar',h:'fina',
 mat:['Papel com um rosto desenhado e linhas no lugar do cabelo','Tesoura sem ponta'],
 hq:['💇😱|O Senhor Papel está com o cabelo enorme!','✂️📞|A Central abre o salão.','✂️〰️|Corte em cima das linhas.','😎✨|Corte novo!'],
 c:'O Senhor Papel quer um corte de cabelo moderno. Você cuida do corte hoje?',
 p:['Desenhe um rosto e, em cima, várias linhas retas e curvas como cabelo.','A criança recorta seguindo as linhas com a tesoura sem ponta.','Depois ela desenha o resto do personagem.'],
 x:'Faça linhas em zigue-zague e espirais para quem já recorta bem.'},
{n:62,e:'🧊',t:'Resgate no Gelo',a:'5-6',min:20,b:2,m:'S',mo:'chuva',h:'rac',
 mat:['Bonequinhos de plástico','1 pote com água congelado na véspera','Colher, água morna e sal'],
 hq:['🧊🦖|Os dinossauros ficaram presos no gelo!','🚑📞|A Central manda a equipe de resgate.','🥄💧|Use água morna, sal e colher.','🦖🎉|Todos livres!'],
 c:'Os dinossauros congelaram! Você descobre o jeito mais rápido de tirar eles do gelo?',
 p:['Na véspera, congele os bonequinhos num pote com água.','Coloque o bloco de gelo numa bacia sobre a toalha.','A criança testa: água morna, sal, colher. O que funciona melhor?'],
 x:'Pergunte por que o gelo derrete e o que aconteceu com o sal.'},
{n:63,e:'🥷',t:'Circuito Ninja',a:'5-6',min:20,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['Almofadas, cadeiras, fita crepe, 1 cesto'],
 hq:['🥷🏯|A escola ninja abriu as inscrições.','📜📞|A Central monta a prova.','🤸🪑|Pule, rasteje e equilibre.','🥋🏅|Faixa preta!'],
 c:'Para entrar na escola ninja, é preciso passar pelo circuito. Valendo?',
 p:['Monte 4 estações: pular almofadas, passar por baixo da mesa, andar na fita, jogar meia no cesto.','A criança faz o circuito inteiro.','Cronometre e tente melhorar o tempo.'],
 x:'Deixe a criança montar um circuito para você.'},
{n:64,e:'📮',t:'Correio da Casa',a:'5-6',min:15,b:1,m:'S',mo:'jantar',h:'ling',
 mat:['1 caixa de sapato (vira caixa de correio)','Papel e lápis de cor'],
 hq:['📮📭|A caixa de correio está vazia.','✉️📞|A Central abre o correio.','🖍️💌|Escreva ou desenhe cartinhas.','📬😍|Cartas entregues!'],
 c:'O correio da casa precisa de cartas para entregar. Você escreve uma para cada pessoa?',
 p:['Faça uma abertura na tampa da caixa e escreva "Correio".','A criança faz desenhos ou bilhetes para cada pessoa da casa.','Depois do jantar, ela entrega as cartas como carteira.'],
 x:'Responda as cartas dela e coloque na caixa para ela abrir no dia seguinte.'},
{n:65,e:'🪞',t:'Espelho Humano',a:'5-6',min:5,b:1,m:'J',mo:'cinco',h:'aten',
 mat:['Nenhum'],
 hq:['🪞✨|Você virou um espelho mágico!','👀📞|A Central testa a sua atenção.','🙆🙆|Copie cada movimento ao mesmo tempo.','😂🏅|Espelho perfeito!'],
 c:'Você agora é o meu espelho. Tudo o que eu fizer, você faz igual. Valendo?',
 p:['Fiquem frente a frente.','Faça movimentos lentos: levantar o braço, tocar o nariz, abrir a boca.','A criança copia ao mesmo tempo. Depois troquem.'],
 x:'Faça os movimentos cada vez mais rápido.'},
{n:66,e:'❓',t:'O Que É, O Que É?',a:'5-6',min:5,b:1,m:'J',mo:'espera',h:'ling',
 mat:['Nenhum'],
 hq:['❓🧠|Chegou uma charada da Central!','🕵️📞|Só um gênio consegue responder.','💬🍌|"É amarelo, é comprido, macaco adora..."','💡😄|Banana!'],
 c:'Eu vou dar pistas de uma coisa. Quantas pistas você precisa para adivinhar?',
 p:['Pense num objeto, bicho ou comida.','Dê uma pista de cada vez: cor, tamanho, onde fica.','A criança tenta adivinhar com o menor número de pistas.'],
 x:'Ela pensa em algo e você precisa adivinhar fazendo perguntas de sim ou não.'},
{n:67,e:'🌌',t:'Céu de Papel',a:'5-6',min:15,b:1,m:'J',mo:'dormir',h:'cria',
 mat:['1 folha de papel escuro ou cartolina','1 lápis','1 lanterna'],
 hq:['🌑😢|O céu do quarto ficou sem estrelas.','⭐📞|A Central manda fazer estrelas novas.','✏️🕳️|Fure o papel com o lápis.','🔦🌌|O teto ficou estrelado!'],
 c:'O céu do seu quarto está sem estrelas. Vamos fazer um céu novo antes de dormir?',
 p:['Coloque o papel sobre uma almofada e deixe a criança furar com a ponta do lápis.','Apague a luz e coloque a lanterna atrás do papel, apontando para o teto.','Deitem e olhem as estrelas aparecendo.'],
 x:'Faça o desenho de uma constelação: um bicho feito de estrelas.'},
{n:68,e:'👟',t:'Loja de Sapatos',a:'5-6',min:15,b:1,m:'S',mo:'jantar',h:'rac',
 mat:['Os sapatos da casa'],
 hq:['👟🌪️|A sapateira virou uma bagunça!','🏪📞|A Central abre uma loja de sapatos.','👞👠|Forme pares e organize do maior ao menor.','🗂️😎|Loja pronta para abrir!'],
 c:'A loja de sapatos vai abrir e tudo está bagunçado. Você organiza as prateleiras?',
 p:['Junte os sapatos da casa num lugar.','A criança forma os pares e coloca em fila do maior para o menor.','Depois ela "vende" os sapatos para cada dono.'],
 x:'Separe os sapatos por tipo: de sair, de ficar em casa e de esporte.'},
];
