// Missões 1–34 (faixa 3–4 anos, exceto a 12)
// Campos: n número · e emoji · t título · a idade · min minutos · b bagunça (1–3) · m modo (J juntos, S sozinho)
// mo momento · h habilidade · mat materiais · hq historinha (4 quadros "emojis|texto") · c convite · p passos · x desafio extra
export default [
{n:1,e:'🧸',t:'Resgate dos Bichinhos',a:'3-4',min:15,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['5 bichinhos de pelúcia ou bonecos','1 caixa (vira o hospital)','Fita crepe'],
 hq:['🧸😟|Os bichinhos se perderam pela casa!','📞🦸|A Central chama: "Agente, precisamos de você!"','🔍🛋️|Procure atrás das almofadas e embaixo da mesa.','🏥💛|Todos salvos e cuidados no hospital!'],
 c:'Agente, os bichinhos se perderam e estão com medo. Você consegue encontrar todos eles?',
 p:['Esconda 5 bichinhos pela sala, deixando um pedacinho de cada um aparecendo.','Dê pistas de "quente" e "frio" enquanto a criança procura.','Cada bichinho encontrado vai para o hospital-caixa e ganha um curativo de fita crepe.'],
 x:'Conte junto quantos bichinhos foram salvos e esconda em lugares mais difíceis na segunda rodada.'},
{n:2,e:'🖌️',t:'Pintor de Água',a:'3-4',min:15,b:1,m:'S',mo:'jantar',h:'motora',
 mat:['1 pincel ou esponja','1 copo com um pouco de água','Um piso, muro ou porta escura'],
 hq:['🧱😮|A parede está sem graça!','🖌️💧|A Central manda um pincel mágico.','🎨✨|Pinte desenhos enormes só com água.','☀️🪄|Eles somem ao secar. É mágica!'],
 c:'Este pincel é mágico: tudo o que você pinta desaparece sozinho. Quer testar?',
 p:['Ofereça o copo com pouca água e o pincel num lugar que pode molhar (varanda, quintal, azulejo).','Mostre um traço e espere secar para ver o desenho sumir.','Deixe a criança pintar o que quiser enquanto você termina o que está fazendo.'],
 x:'Peça para pintar um sol, uma casa e uma pessoa antes que o primeiro desenho desapareça.'},
{n:3,e:'🚗',t:'Lava-Rápido de Carrinhos',a:'3-4',min:20,b:2,m:'S',mo:'jantar',h:'auto',
 mat:['Carrinhos ou bonecos de plástico','1 bacia com água e um pouco de sabão','Escova de dente velha e um pano'],
 hq:['🚗🟫|Os carrinhos voltaram cheios de lama!','🧽📞|A Central abre o lava-rápido.','🫧🪥|Esfregue cada carro com a escovinha.','✨🚗|Carros brilhando, prontos para correr!'],
 c:'O lava-rápido abriu e tem uma fila de carros sujos esperando. Você assume o comando da lavagem?',
 p:['Coloque uma toalha no chão e a bacia em cima.','Mostre como esfregar com a escova e secar com o pano.','Monte uma "fila" de carros sujos e um "estacionamento" para os limpos.'],
 x:'Cobre "moedas" de papel pela lavagem e deixe a criança dar o troco.'},
{n:4,e:'🐻',t:'Piquenique dos Ursos',a:'3-4',min:20,b:1,m:'J',mo:'chuva',h:'ling',
 mat:['1 toalha ou lençol','Pratinhos e copinhos de brinquedo ou de plástico','Bichinhos de pelúcia'],
 hq:['🐻🌧️|Os ursos queriam um piquenique, mas choveu.','🏠💡|A Central tem uma ideia: piquenique na sala!','🍽️🧸|Sirva cada convidado e pergunte o que ele quer.','😊🎉|Que festa gostosa!'],
 c:'Os ursos estão com fome e a chuva estragou o passeio. Você organiza um piquenique aqui dentro?',
 p:['Estenda a toalha no chão e sente os bichinhos em roda.','A criança serve cada convidado e "conversa" com ele.','Faça perguntas: "O urso gosta de quê? Ele está feliz ou triste?"'],
 x:'Peça para a criança contar a você como foi o piquenique, do começo ao fim.'},
{n:5,e:'🦘',t:'Pula-Pula das Cores',a:'3-4',min:10,b:1,m:'J',mo:'cinco',h:'motora',
 mat:['4 folhas de papel colorido (ou desenhe círculos coloridos em folhas brancas)'],
 hq:['🟥🟦|Apareceram ilhas coloridas no chão!','🦘📞|A Central abre o teste de pulos.','👂🟨|Escute a cor e pule nela bem rápido!','🏅😄|Pulos de campeão!'],
 c:'Só pode pisar na cor que eu falar. Valendo?',
 p:['Espalhe as folhas no chão, uma longe da outra.','Fale uma cor e a criança pula até ela.','Vá aumentando a velocidade.'],
 x:'Fale duas cores seguidas ("vermelho, depois azul") para treinar a memória.'},
{n:6,e:'🧦',t:'Par Perfeito',a:'3-4',min:10,b:1,m:'S',mo:'jantar',h:'rac',
 mat:['Um monte de meias limpas e misturadas'],
 hq:['🧦🌪️|Um furacão misturou todas as meias!','📞🕵️|A Central chama um reforço: você!','👀🧦|Encontre as meias que são iguais.','🧺✅|Todas com o seu par!'],
 c:'Um furacão bagunçou as meias e elas perderam seus pares. Você ajuda cada uma a achar a irmã?',
 p:['Despeje as meias limpas num cesto ou no sofá.','A criança procura as iguais e coloca lado a lado.','No fim, contem juntos quantos pares ela formou.'],
 x:'Separe as meias por dono: as do papai, as da mamãe e as dela.'},
{n:7,e:'🧑‍🍳',t:'Chef por um Dia',a:'3-4',min:20,b:2,m:'J',mo:'jantar',h:'auto',
 mat:['Pão, banana ou outras frutas macias','Faca sem ponta','Prato e avental (opcional)'],
 hq:['🍽️😋|A família está com fome!','👩‍🍳📞|A Central contrata um novo chef.','🍌🔪|Corte a banana com a faca sem ponta.','🥪⭐|Lanche pronto e servido pelo chef!'],
 c:'O restaurante vai abrir e falta quem cozinhe. Você aceita comandar a cozinha hoje?',
 p:['Lave as mãos juntos e coloque o avental.','A criança corta a banana com a faca sem ponta e monta o lanche no prato.','Ela serve a família e anuncia o nome do prato.'],
 x:'Invente um nome engraçado para o lanche e faça um cardápio desenhado.'},
{n:8,e:'🔍',t:'Detetive de Formas',a:'3-4',min:10,b:1,m:'J',mo:'cinco',h:'rac',
 mat:['Nenhum (só olhar pela casa)'],
 hq:['⭕🟥|As formas fugiram do livro!','🕵️📞|A Central abre uma investigação.','🔍🏠|Ache coisas redondas e quadradas pela casa.','🗂️🏅|Formas encontradas!'],
 c:'As formas fugiram e se esconderam nos objetos da casa. Você consegue achar 3 coisas redondas?',
 p:['Desenhe ou mostre com o dedo um círculo, um quadrado e um triângulo.','Peça para achar 3 coisas redondas (prato, relógio, botão).','Depois 3 quadradas e, por último, triangulares.'],
 x:'Peça para desenhar as coisas que encontrou.'},
{n:9,e:'🌈',t:'Arco-íris de Brinquedos',a:'3-4',min:15,b:1,m:'S',mo:'chuva',h:'rac',
 mat:['Brinquedos de várias cores'],
 hq:['🌧️☁️|A chuva apagou o arco-íris!','🌈📞|A Central precisa montar um novo.','🔴🟡|Junte os brinquedos de cada cor numa fila.','🌈😍|O arco-íris voltou!'],
 c:'A chuva apagou o arco-íris do céu. Vamos montar um novo no chão com os seus brinquedos?',
 p:['Mostre a ordem das cores: vermelho, laranja, amarelo, verde, azul e roxo.','A criança procura brinquedos de cada cor e faz uma fila no chão.','Tire uma foto mental e depois guardem tudo por cor.'],
 x:'Conte quantos brinquedos tem em cada cor. Qual faixa ficou maior?'},
{n:10,e:'🐢',t:'Corrida dos Bichos',a:'3-4',min:10,b:1,m:'J',mo:'cinco',h:'motora',
 mat:['Fita crepe ou uma almofada para marcar a chegada'],
 hq:['🏁🐾|Vai começar a grande corrida da floresta!','🐸🐢|Cada rodada é com um bicho diferente.','🦀🐍|Corra como sapo, caranguejo e cobra.','🏆🥇|Todo mundo ganhou medalha!'],
 c:'A corrida da floresta vai começar e cada rodada é com um bicho diferente. Qual você quer ser primeiro?',
 p:['Marque a largada e a chegada no chão.','Fale um bicho: sapo pula, tartaruga vai devagar, caranguejo anda de lado, cobra rasteja.','Corram juntos e troquem de bicho a cada rodada.'],
 x:'A criança escolhe o bicho e você tem que imitar.'},
{n:11,e:'🥁',t:'Banda da Cozinha',a:'3-4',min:15,b:1,m:'S',mo:'jantar',h:'cria',
 mat:['Panelas e potes de plástico','Colheres de pau','1 pote fechado com arroz (vira chocalho)'],
 hq:['🎵😴|A cozinha está silenciosa demais.','🥁📞|A Central monta uma banda.','🍲🥄|Toque as panelas, o pote e o chocalho.','🎶🌟|Que show!'],
 c:'A banda da cozinha precisa de um baterista. Você toca enquanto eu preparo o jantar?',
 p:['Separe panelas de plástico ou alumínio e colheres de pau no chão da cozinha.','Feche bem um pote com arroz para virar chocalho.','A criança toca enquanto você cozinha. Peça músicas lentas e rápidas.'],
 x:'Você bate um ritmo e ela repete igualzinho.'},
{n:12,e:'🏘️',t:'Cidade de Papel',a:'5-6',min:20,b:1,m:'J',mo:'chuva',h:'fina',
 mat:['Folhas de papel','Giz de cera ou lápis de cor'],
 hq:['🏘️💨|A cidade sumiu!','🦸📞|Só você pode salvar.','📄🖍️|Pegue papel e giz.','🏗️🎉|Construa!'],
 c:'Agente, os moradores ficaram sem casa! Você aceita construir uma cidade nova?',
 p:['Dobre a folha ao meio para fazer a casinha em pé.','Desenhe portas, janelas e telhado.','Faça uma rua em outra folha e monte a cidade.'],
 x:'Dê nome para a cidade e invente quem mora em cada casa.'},
{n:13,e:'🔦',t:'Lanterna das Sombras',a:'3-4',min:10,b:1,m:'J',mo:'dormir',h:'cria',
 mat:['1 lanterna','Uma parede clara'],
 hq:['🌙🧱|A parede do quarto virou cinema.','🔦📞|A Central acende a lanterna.','🖐️🐦|Faça bichos de sombra com as mãos.','😴💛|Boa noite, bichinhos!'],
 c:'Hoje o cinema é na parede do quarto. Vamos fazer bichos de sombra antes de dormir?',
 p:['Apague a luz e aponte a lanterna para a parede.','Mostre como fazer um passarinho, um cachorro e um coelho com as mãos.','Deixe a criança inventar os bichos dela e contar o que eles fazem.'],
 x:'Termine com o bicho de sombra "indo dormir" bem devagar.'},
{n:14,e:'🐉',t:'Respiração do Dragão',a:'3-4',min:5,b:1,m:'J',mo:'dormir',h:'emo',
 mat:['Nenhum'],
 hq:['🐉🔥|O dragãozinho está muito agitado.','🌬️📞|A Central ensina o sopro mágico.','😮‍💨🐉|Encha a barriga de ar e solte o fogo devagar.','😌✨|Dragão calminho e pronto para dormir.'],
 c:'Vamos virar dragões e soltar fogo bem devagarinho, para o dragão ficar calmo?',
 p:['Sentem um de frente para o outro.','Puxem o ar pelo nariz enchendo a barriga, contando até 3.','Soltem o ar pela boca bem devagar, como um fogo comprido. Repitam 5 vezes.'],
 x:'Use quando a criança estiver nervosa: "Vamos fazer a respiração do dragão?"'},
{n:15,e:'📚',t:'Agora Quem Conta Sou Eu',a:'3-4',min:10,b:1,m:'J',mo:'dormir',h:'ling',
 mat:['1 livro ilustrado que a criança conhece'],
 hq:['📚😴|O contador de histórias ficou com sono.','🎙️📞|A Central chama um novo contador.','👀🖼️|Conte a história olhando as figuras.','👏📖|Que história bonita!'],
 c:'Hoje quem vai contar a história é você. Eu sou a plateia!',
 p:['Escolham um livro que a criança já conhece.','Ela vira as páginas e conta o que vê nas figuras, do jeito dela.','Faça perguntas: "E depois? Como ele se sentiu?"'],
 x:'Peça para inventar um final diferente para a história.'},
{n:16,e:'🧺',t:'Basquete de Meias',a:'3-4',min:10,b:1,m:'S',mo:'cinco',h:'motora',
 mat:['3 pares de meias enrolados em bolinha','1 cesto de roupa ou balde'],
 hq:['🧦🏀|As meias viraram bolas de basquete!','🧺📞|A Central monta a quadra.','🎯🙌|Acerte a cesta de longe.','🏆🎉|Cesta!'],
 c:'Vamos ver quantas cestas você faz antes de eu terminar de lavar a louça?',
 p:['Enrole as meias em bolinhas.','Coloque o cesto a 1 metro e marque o lugar de arremesso.','A cada 3 acertos, dê um passo para trás.'],
 x:'Conte as cestas em voz alta até 10.'},
{n:17,e:'🐟',t:'Pescaria no Tapete',a:'3-4',min:15,b:1,m:'J',mo:'chuva',h:'fina',
 mat:['Papel e lápis de cor','Tesoura (para o adulto)','1 pregador de roupa'],
 hq:['🌊🐟|Os peixes estão nadando no tapete!','🎣📞|A Central libera a pescaria.','🫳🐠|Pegue cada peixe com o pregador.','🪣😄|Pescaria cheia!'],
 c:'O tapete virou mar e está cheio de peixes. Você consegue pescar todos com o pregador?',
 p:['Desenhe e recorte 8 peixes simples (a criança pinta).','Espalhe os peixes no tapete.','A criança pega cada peixe só com o pregador e coloca no "balde".'],
 x:'Escreva números nos peixes e some os pontos de cada pescaria.'},
{n:18,e:'🏕️',t:'Cabana do Explorador',a:'3-4',min:30,b:2,m:'J',mo:'chuva',h:'cria',
 mat:['1 lençol','2 cadeiras','Almofadas e uma lanterna'],
 hq:['🗺️🧭|O explorador precisa de um acampamento.','🏕️📞|A Central manda montar uma cabana.','🪑🛏️|Use cadeiras, lençol e almofadas.','🔦😍|Acampamento pronto para a aventura!'],
 c:'Todo explorador precisa de uma base secreta. Vamos construir a sua?',
 p:['Coloque 2 cadeiras afastadas e jogue o lençol por cima.','Prenda as pontas com livros e forre o chão com almofadas.','Dentro da cabana, leiam um livro ou contem histórias com a lanterna.'],
 x:'Crie uma senha secreta para entrar na cabana.'},
{n:19,e:'🥢',t:'Pegador Maluco',a:'3-4',min:10,b:1,m:'S',mo:'jantar',h:'fina',
 mat:['1 pegador de salada ou de macarrão','10 bolinhas de papel amassado','2 potes'],
 hq:['📄⚪|As bolinhas de neve caíram no pote errado.','🥢📞|A Central entrega um pegador especial.','🫳⚪|Passe uma por uma para o outro pote.','✅❄️|Missão cumprida!'],
 c:'As bolinhas de neve precisam mudar de casa, mas não pode usar a mão. Você consegue?',
 p:['Amasse 10 bolinhas de papel e coloque num pote.','A criança passa uma a uma para o outro pote usando o pegador.','Conte o tempo e tente bater o recorde.'],
 x:'Afaste os potes e peça para levar uma bolinha de cada vez andando.'},
{n:20,e:'🧻',t:'Lenço que Voa',a:'3-4',min:5,b:1,m:'J',mo:'cinco',h:'motora',
 mat:['1 lenço de papel'],
 hq:['🧻🌬️|Um lenço aprendeu a voar!','👀📞|A Central quer saber: quem pega primeiro?','🙌⬆️|Jogue para cima e pegue antes de cair.','🎉🏅|Pegou!'],
 c:'Esse lenço voa devagarinho. Você consegue pegar antes de ele tocar o chão?',
 p:['Abra o lenço e jogue bem alto.','A criança tenta pegar antes de cair.','Depois tente pegar com o cotovelo, com a cabeça ou com o pé.'],
 x:'Soprem o lenço juntos para mantê-lo no ar o máximo possível.'},
{n:21,e:'🐾',t:'Siga a Pegada',a:'3-4',min:15,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['Papel','Lápis','Tesoura (para o adulto)','Um brinquedo como "tesouro"'],
 hq:['🐾❓|Apareceram pegadas misteriosas na casa!','🕵️📞|A Central pede para seguir a trilha.','👣🚪|Siga pegada por pegada.','🎁😮|Achou o tesouro no fim!'],
 c:'Alguém deixou pegadas pela casa. Vamos descobrir aonde elas levam?',
 p:['Contorne o pé da criança no papel e recorte 8 pegadas.','Monte uma trilha pela casa terminando num brinquedo escondido.','A criança segue as pegadas até achar o tesouro.'],
 x:'Na próxima vez, ela monta a trilha para você seguir.'},
{n:22,e:'🍥',t:'Massinha Caseira',a:'3-4',min:25,b:3,m:'J',mo:'chuva',h:'fina',
 mat:['2 xícaras de farinha de trigo','1 xícara de sal','1 xícara de água','1 colher de óleo','Corante alimentício (opcional)'],
 hq:['🧪📞|A Central perdeu a receita da massa mágica!','🥣🧂|Misture farinha, sal, água e óleo.','✋🌈|Amasse até ficar macia e colorida.','🐍🍪|Agora é só modelar!'],
 c:'Vamos fazer massinha de verdade, do zero, e depois modelar o que você quiser?',
 p:['Misture farinha e sal numa tigela.','Acrescente a água aos poucos, o óleo e o corante. A criança amassa com as mãos.','Modelem cobrinhas, bolinhas e biscoitos de mentira.'],
 x:'Guarde num pote fechado na geladeira: dura vários dias.'},
{n:23,e:'🧽',t:'Missão Brilho',a:'3-4',min:10,b:1,m:'S',mo:'jantar',h:'auto',
 mat:['1 pano úmido','1 borrifador com água (opcional)'],
 hq:['🍽️😬|A mesa está cheia de migalhas.','🧽📞|A Central chama a equipe de limpeza.','💦🫳|Limpe a mesa e as cadeiras.','✨😎|Tudo brilhando!'],
 c:'A mesa do jantar precisa ficar brilhando antes de servir. Você comanda a equipe de limpeza hoje?',
 p:['Entregue um pano úmido e um borrifador com água pura.','A criança limpa a mesa e os assentos das cadeiras.','Elogie o trabalho e peça para ela ajudar a pôr os guardanapos.'],
 x:'Dê uma "estrela de limpeza" desenhada no papel quando terminar.'},
{n:24,e:'🪞',t:'Caretas no Espelho',a:'3-4',min:5,b:1,m:'J',mo:'cinco',h:'emo',
 mat:['1 espelho'],
 hq:['🪞😐|O espelho está sem graça.','😄📞|A Central quer ver todas as caras!','😠😢|Faça cara de bravo, triste e surpreso.','🤣💛|Que caretas divertidas!'],
 c:'Vamos fazer caretas no espelho? Eu falo um sentimento e você mostra a cara dele.',
 p:['Fiquem juntos na frente do espelho.','Fale um sentimento: feliz, triste, bravo, com medo, surpreso.','A criança faz a careta e você adivinha. Depois troquem.'],
 x:'Pergunte: "Quando você fica com essa cara?"'},
{n:25,e:'🗿',t:'Estátua!',a:'3-4',min:10,b:1,m:'J',mo:'cinco',h:'aten',
 mat:['Nenhum (você canta ou bate palmas)'],
 hq:['🎶💃|Todo mundo dançando!','🛑📞|A Central grita: estátua!','🗿😶|Fique paradinha, sem rir.','😂🏆|Quem riu, paga uma dança!'],
 c:'Quando a música parar, todo mundo vira estátua. Topa?',
 p:['Cante uma música ou bata palmas enquanto a criança dança.','Pare de repente e grite "Estátua!".','Quem se mexer ou rir primeiro faz uma dança engraçada.'],
 x:'Diga como deve ser a estátua: "estátua de gato", "estátua de bailarina".'},
{n:26,e:'🛁',t:'Afunda ou Boia?',a:'3-4',min:15,b:2,m:'J',mo:'chuva',h:'rac',
 mat:['1 bacia com água','Objetos de casa: colher, rolha, tampa, esponja, pedra, folha'],
 hq:['🧪❓|Os cientistas têm uma pergunta.','🛁📞|A Central monta o laboratório.','🤔💧|Será que afunda ou boia?','📋🎓|Experiência concluída!'],
 c:'Hoje o laboratório é seu. Vamos descobrir o que afunda e o que boia?',
 p:['Coloque a bacia sobre uma toalha e separe 8 objetos.','Antes de jogar cada um, a criança tenta adivinhar.','Separem em dois montes: os que afundaram e os que boiaram.'],
 x:'Pegue um objeto que afundou e tente fazê-lo boiar (em cima de uma tampa, por exemplo).'},
{n:27,e:'🦉',t:'Boa Noite, Casa',a:'3-4',min:5,b:1,m:'J',mo:'dormir',h:'emo',
 mat:['Nenhum'],
 hq:['🌙🏠|A casa também vai dormir.','🦉📞|A Coruja da Central faz a ronda.','👋🛋️|Dê boa noite a cada cômodo e brinquedo.','🛏️😴|Agora é a sua vez de dormir.'],
 c:'Antes de você dormir, a casa toda precisa ouvir boa noite. Vamos fazer a ronda?',
 p:['Andem pela casa de mãos dadas, falando baixinho.','Deem boa noite para a sala, a cozinha, os brinquedos e as plantas.','Terminem no quarto: boa noite, cama; boa noite, travesseiro.'],
 x:'Faça sempre na mesma ordem: vira um ritual que ajuda a dormir.'},
{n:28,e:'🌋',t:'Ilhas de Almofada',a:'3-4',min:10,b:1,m:'J',mo:'chuva',h:'motora',
 mat:['Almofadas e travesseiros'],
 hq:['🌋😱|O chão virou lava!','🛟📞|A Central joga ilhas de salvamento.','🦶🛋️|Pule de almofada em almofada.','🏝️🎉|Chegou à ilha segura!'],
 c:'Cuidado! O chão virou lava. Você consegue atravessar a sala só pisando nas almofadas?',
 p:['Espalhe as almofadas no chão, perto umas das outras.','A criança atravessa pulando só nas almofadas.','Vá afastando um pouquinho para aumentar o desafio.'],
 x:'Atravessar carregando um bichinho que não pode cair.'},
{n:29,e:'📦',t:'Caixa Misteriosa',a:'3-4',min:10,b:1,m:'J',mo:'cinco',h:'ling',
 mat:['1 caixa ou sacola','Objetos da casa: colher, meia, escova, bola'],
 hq:['📦❓|Chegou uma caixa misteriosa!','🙈📞|A Central avisa: proibido olhar.','✋🤔|Coloque a mão e descubra pelo tato.','💡😄|Acertou!'],
 c:'Tem uma coisa escondida nessa caixa. Você consegue descobrir só tocando, sem olhar?',
 p:['Coloque um objeto dentro da caixa sem a criança ver.','Ela põe a mão e descreve: "é duro, é gelado, é comprido".','Ela tenta adivinhar e depois confere.'],
 x:'Troquem: ela esconde e você adivinha.'},
{n:30,e:'🌱',t:'Jardineiro do Feijão',a:'3-4',min:15,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['1 copo transparente','Algodão','3 grãos de feijão (o adulto manuseia)','Água'],
 hq:['🌱💤|Um feijão quer virar planta.','🧑‍🌾📞|A Central pede alguém para cuidar dele.','💧☀️|Coloque no algodão e regue todo dia.','🌿😍|Ele cresceu!'],
 c:'Esse feijão quer virar uma planta, mas precisa de alguém que cuide dele. Você aceita?',
 p:['A criança coloca o algodão no copo e você coloca os feijões.','Ela molha o algodão com um pouquinho de água.','Deixem perto da janela e observem todos os dias.'],
 x:'Desenhe o feijão a cada 2 dias para ver o quanto ele cresceu.'},
{n:31,e:'🛒',t:'Mercadinho',a:'3-4',min:20,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['Embalagens vazias e limpas','Papel para fazer dinheiro','1 sacola'],
 hq:['🏪🚪|O mercadinho vai abrir!','🛒📞|A Central contrata um caixa.','💵🧃|Venda os produtos e conte o dinheiro.','🛍️😄|Cliente satisfeito!'],
 c:'O mercadinho abriu e eu sou a primeira cliente. Quanto custa este suco?',
 p:['Organize as embalagens numa mesa como prateleira.','Faça notas de papel de 1, 2 e 5.','Revezem: um é o caixa e o outro é o cliente.'],
 x:'Faça uma lista de compras desenhada para o cliente seguir.'},
{n:32,e:'🛣️',t:'Estrada de Fita',a:'3-4',min:15,b:1,m:'S',mo:'jantar',h:'motora',
 mat:['Fita crepe','Carrinhos'],
 hq:['🚗🚫|Os carrinhos estão sem estrada.','🛣️📞|A Central manda construir uma.','🛞➰|Siga as curvas sem sair da pista.','🏁🎉|Chegaram!'],
 c:'Os carrinhos precisam de uma estrada cheia de curvas. Você dirige sem sair da pista?',
 p:['Cole fita crepe no chão formando uma estrada com curvas.','A criança passa os carrinhos pela estrada.','Depois ela mesma anda pela linha, como equilibrista.'],
 x:'Desenhe uma "garagem" e um "posto" no fim da estrada.'},
{n:33,e:'🧩',t:'Quebra-Cabeça de Caixa',a:'3-4',min:15,b:1,m:'J',mo:'chuva',h:'rac',
 mat:['1 caixa de cereal ou de biscoito vazia','Tesoura (para o adulto)'],
 hq:['🧩💥|A figura da caixa se partiu!','🔧📞|A Central pede para montar de novo.','🤔🧩|Encaixe as peças certinhas.','🖼️✅|Montou!'],
 c:'A figura da caixa quebrou em pedaços. Você consegue montar de novo?',
 p:['Recorte a frente da caixa em 4 pedaços (para 3 anos) ou 6 (para 4 anos).','Misture as peças.','A criança monta. Depois vocês trocam de caixa.'],
 x:'Corte em mais pedaços na segunda rodada.'},
{n:34,e:'🧸',t:'Ursinho Sobe e Desce',a:'3-4',min:5,b:1,m:'J',mo:'dormir',h:'emo',
 mat:['1 bichinho de pelúcia'],
 hq:['🧸🎢|O ursinho quer andar de barco.','🌊📞|A barriga vira um mar calminho.','😮‍💨🧸|Respire e veja o ursinho subir e descer.','😴🌙|O ursinho dormiu.'],
 c:'Seu ursinho quer dormir num barquinho. Vamos fazer o mar na sua barriga?',
 p:['A criança deita de barriga para cima com o bichinho em cima da barriga.','Ela respira fundo e vê o ursinho subir; solta o ar e ele desce.','Façam 10 respirações bem devagar, falando baixinho.'],
 x:'Conte as ondas baixinho até o ursinho "dormir".'},
];
